version: "3"

services:
  database:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - data:/data/db
    networks:
      - network

  server:
    build: ./server
    ports:
      - 9000:5000
    environment:
      DATABASE_URL: mongodb://database/
    networks:
      - network

  client:
    build: ./client
    ports:
      - 5000:5173
    environment:
      - VITE_BACKEND_URL=http://localhost:9000
    networks:
      - network

volumes:
  data:

networks:
  network: